import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm

# 1. Load the CSV generated by Java
data = pd.read_csv('TERRAIN_GENERATOR/terrain_matrix.csv', header=None).values

# 2. Create X and Y coordinates based on the matrix dimensions
N = data.shape[0] # Number of rows
M = data.shape[1] # Number of columns

# Create a meshgrid for the X and Y coordinates
X = np.arange(0, M, 1)
Y = np.arange(0, N, 1)
X, Y = np.meshgrid(X, Y)

# Z is our matrix data
Z = data

# 3. Set up the 3D plot
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Plot the surface. Use a colormap (cm.viridis) to map Z heights to colors
surf = ax.plot_surface(X, Y, Z, cmap=cm.viridis, edgecolor='none', alpha=0.9)

# --- THE NEW LINE: Lock the Z-axis to always be exactly 0 to 1 ---
ax.set_zlim(0, 1)

# Add a color bar and labels
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=5, label='Elevation (0 to 1)')
ax.set_title('3D Terrain Generation Matrix')
ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.set_zlabel('Height (Z)')

# 4. Show the interactive plot
plt.show()